---
title: "Errata"
---

Last updated `r format(Sys.Date(), "%B %e, %Y")`

## Known Errors in the 2nd edition

- [File an issue](https://www.github.com/mdsr-book/mdsr2e/issues)
- Problem 11 in Chapter 6 should refer to the "approach described in Section 6.4.1.2" instead of Section 5.5.4. (nhorton)

## BibTeX entry

```
@book{baumer2021mdsr,
  title={{Modern Data Science with R}},
  author={Benjamin S. Baumer and Daniel T. Kaplan and Nicholas J. Horton},
  year={2021},
  month={3},
  day={12},
  edition={2nd},
  pages={1--673},
  publisher={Chapman and Hall/CRC Press: Boca Raton},
  isbn={9780367191498},
  url={https://www.routledge.com/Modern-Data-Science-with-R/Baumer-Kaplan-Horton/p/book/9780367191498}
}
```

<hr>

## Known Errors in the 1st edition

### To be fixed for the third printing

- Page 11: The caption should say "USD" instead of "millions of USD". (rporta)
- Page 37: The end of the last sentence should read "corresponds to a value of 30 roadways per unit area". (mhilton)
- Page 91: The key for the Google spreadsheet has changed. Try `hiv_key <- "1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA"` instead. (mwan)
- Page 156: "We can compare this to a (hypothetical) sample of size $n = 1,000$" should be "We can compare this to a (hypothetical) sample of size $n = 200$" (zzhang)
- Page 282: A comma is missing in the SQL query that causes the `dest` column to be erroneously labelled `flight`. (kbaker)
- Page 310-313: There is inconsistent usage of `babynamedb` and `babynamedata`. All references should be to `babynamedb`. (kbaker)
- Page 378: "The *diameter* of a graph is the length of the longest geodesic between any [two] pairs of vertices." The word "two" should be removed. (agary)
- Page 379: A parenthesis is missing after "(see Figure 16.1". (bbaumer)

### Fixed for the second printing

- Page 10: The last sentence should start "It also seems clear" instead of "In also seems clear". (voberholzer)
- Page 36: In the caption to Figure 3.4, it should read "`roadways` is mapped to size", instead of "`educ` is mapped to size." (gmontoya)
- Page 65: The `filter()` command on the `start` variable at the bottom of the page does not work as intended. The argument should be `start > "1973-01-01"`. ([sschmidt](https://github.com/mdsr-book/mdsr-book.github.io/issues/15))
- Page 90: At the end of Exercise 4.16, the following sentence should be added: "Use the `Births78` data set from the `mosaicData` package as a reference." (nhorton/bbaumer)
- Page 214: It's not clear where `Votes_wide` comes from. It's shown in Table 9.1 and the code to generate it is (lkaganovskiy): 
    ```{r, eval=FALSE}
    library(mdsr)
    Votes_wide <- Votes %>%
      tidyr::spread(key = bill, value = vote)
    ```
- Page 375: Exercise 15.4 should read: "Find all of the adjectives in one of Shakespeare's plays that end in `more` or `less`." (nhorton/bbaumer)
- Page 375: Exercise 15.5 should read: "Find all of the lines containing the stage direction `Exit` or `Exeunt` in one of Shakespeare's plays." (nhorton/bbaumer)
- Page 399: Lambert Conformal Conic projection is misspelled. (nhorton)
- Page 465: The residuals should be defined as $\hat{\epsilon}_i = y_i - \hat{y}_i$. ([alanarnholt](https://github.com/mdsr-book/mdsr-book.github.io/issues/14))

## BibTeX entry

```
@book{baumer2017mdsr,
  title={{Modern Data Science with R}},
  author={Benjamin S. Baumer and Daniel T. Kaplan and Nicholas J. Horton},
  year={2017},
  month={2},
  day={10},
  pages={1--582},
  publisher={Chapman and Hall/CRC Press: Boca Raton},
  isbn={9781498724487},
  url={https://www.crcpress.com/Modern-Data-Science-with-R/Baumer-Kaplan-Horton/9781498724487}
}
```

