---
title: "Publicity"
---


- 2nd edition journal reviews:
    - [Kohma Arai and Vyacheslav Lyubchich](https://doi.org/10.1080/00401706.2022.2087421), *Technometrics*, vol. 64, no. 3, pp. 429--429, 26 Jul. 2022.
    - [Annika Hoyer](https://doi.org/10.1002/bimj.202100258), *Biometrical Journal*, 13 Sep 2021. 

- 1st edition journal reviews: 
    - [Allan M. Miller](https://dl.acm.org/citation.cfm?id=3300155&dl=ACM&coll=DL), *ACM SIGACT News*, vol. 49, no. 4, pp. 13--16, Dec 2018.
    - [Jordi Prats](https://www.significancemagazine.com/science/596-r-book-review-two-approaches-to-learning-data-science), *Significance*, 21 Aug 2018.
    - [Andrew Bray](https://amstat.tandfonline.com/doi/pdf/10.1080/00031305.2018.1496649), *The American Statistician*, vol. 72, no. 3, pp. 295--297, Aug 2018.
    - [Shuangzhe Liu](https://onlinelibrary.wiley.com/doi/pdf/10.1111/insr.12256), *International Statistical Review*, vol. 86, no. 1, pp. 162, Apr 2018.
    - [Tim Downie](http://dx.doi.org/10.18637/jss.v080.b02), *Journal of Statistical Software*, vol. 80, no. 2, Aug 2017.
- Robert Hayden, [Modern Data Science with R](http://www.maa.org/press/maa-reviews/modern-data-science-with-r?r=mathfeed), MAA Press
- Murtaza Haider, [*Modern Data Science with R: A review*](https://medium.com/@regionomics/modern-data-science-with-r-a-review-af45161af161)
- [CRC Press interview with Ben Baumer](https://www.crcpress.com/go/baumer_interview?utm_source=CRCPress&utm_medium=cms&utm_campaign=170200780)

- Tweets:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/jo_hardin47?ref_src=twsrc%5Etfw">@jo_hardin47</a> plugging <a href="https://twitter.com/BaumerBen?ref_src=twsrc%5Etfw">@BaumerBen</a>, Danny Kaplan and <a href="https://twitter.com/askdrstats?ref_src=twsrc%5Etfw">@askdrstats</a>&#39; book, Modern Data Science with R, particularly the chapter on ethics. Freely available to download! <a href="https://t.co/fKQInliXTW">https://t.co/fKQInliXTW</a> <a href="https://twitter.com/hashtag/icots10?src=hash&amp;ref_src=twsrc%5Etfw">#icots10</a></p>&mdash; Amelia McNamara (@AmeliaMN) <a href="https://twitter.com/AmeliaMN/status/1016563864664793090?ref_src=twsrc%5Etfw">July 10, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Just got my copy! I should try to get this autographed :) <a href="https://twitter.com/BaumerBen">@BaumerBen</a> <a href="https://twitter.com/askdrstats">@askdrstats</a> <a href="https://t.co/ZSwKsaE2kY">pic.twitter.com/ZSwKsaE2kY</a></p>&mdash; Mine CetinkayaRundel (@minebocek) <a href="https://twitter.com/minebocek/status/834430820475629568">February 22, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Excited to get this in the mail! Modern Data Science w R by <a href="https://twitter.com/BaumerBen">@BaumerBen</a> Danny Kaplan and <a href="https://twitter.com/askdrstats">@askdrstats</a> <a href="https://t.co/3Cv3p5RB83">pic.twitter.com/3Cv3p5RB83</a></p>&mdash; Miles Ott (@Miles_Ott) <a href="https://twitter.com/Miles_Ott/status/831138723249156096">February 13, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-cards="hidden" data-lang="en"><p lang="en" dir="ltr">Now available: Modern <a href="https://twitter.com/hashtag/DataScience?src=hash">#DataScience</a> with <a href="https://twitter.com/hashtag/Rstats?src=hash">#Rstats</a> by <a href="https://twitter.com/BaumerBen">@BaumerBen</a>, Daniel Kaplan and <a href="https://twitter.com/askdrstats">@askdrstats</a> from <a href="https://twitter.com/CRC_MathStats">@CRC_MathStats</a> <a href="https://t.co/L7CqP4u6yh">https://t.co/L7CqP4u6yh</a> <a href="https://t.co/lFKVKxkLp1">pic.twitter.com/lFKVKxkLp1</a></p>&mdash; Math &amp; Statistics (@CRC_MathStats) <a href="https://twitter.com/CRC_MathStats/status/823553342425202688">January 23, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

